### ISSUE TITLE
Cria a parte do administrador primeiro

### ISSUE THREAD

**Issue by gutorc92** [Xmaquina/site#1]
A parte do administrador vai ser usada para fazer a integração com o servidor, seria bom implementa-la primeiro.

**Comment by allanpereiras** [comment]
Ok

Em 4 de abr de 2017 5:46 PM, "Gustavo Coelho" <notifications@github.com>
escreveu:

A parte do administrador vai ser usada para fazer a integração com o
servidor, seria bom implementa-la primeiro.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/Xmaquina/site/issues/1>, or mute the thread
